# ~/.tmux.conf

set -g default-terminal "tmux-256color"
set-option -sa terminal-features ',xterm-256color:RGB'

# Set leader key to Ctrl-S
unbind C-b
set -g prefix C-s

set -g set-titles on

set -g default-command fish

set -g status-keys vi
set -g history-limit 10000

setw -g mode-keys vi
setw -g mouse on
setw -g monitor-activity on

set -g focus-events on

# Start windows and panes at 1, not 0
set -g renumber-windows on
set -g base-index 1
setw -g pane-base-index 1

# Enable VIM motions
setw -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'y' send -X copy-selection

bind-key t copy-mode

bind-key x kill-pane

bind-key v split-window -h
bind-key d split-window -v

bind-key J resize-pane -D 5
bind-key K resize-pane -U 5
bind-key H resize-pane -L 5
bind-key L resize-pane -R 5

bind-key M-j resize-pane -D 
bind-key M-k resize-pane -U
bind-key M-h resize-pane -L
bind-key M-l resize-pane -R

# Use Alt-vim keys without prefix key to switch panes
bind -n M-h select-pane -L
bind -n M-j select-pane -D 
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# No delay for escape key press
set -sg escape-time 0

# Improve the status bar. The default status bar places the session ID
# to the left, but I rarely have more than one session. I do, however,
# care about the hostname, so hostname:session_id followed by month,
# day, and current time is useful context for the lower right.
set -g status-position bottom
set -g status-left ""
set -g status-left-length 60
set -g status-right " #h:#S "

# If we support at least 256 colors, give the tmux status bar a nice
# amber glow, reminiscent of old amber phosphor CRTs. Also, render the
# active window with a slightly brighter background, so it stands out
# clearly.
#if "[ $(tput colors) -ge 256 ]" {
#  set -g status-left-style "fg=orange"
#  set -g status-right-style "fg=orange"
#  set -g status-style "fg=orange bg=#202d46"
#  set -g message-style "fg=black bg=colour172"
#  # Current window should be slightly brighter.
#  set -g window-status-current-style "fg=orange bg=#374e7b"
#  # Windows with activity should be very subtly highlighted.
#  set -g window-status-activity-style "fg=colour17 bg=colour130"
#  set -g mode-style "fg=black bg=colour172"
#}

# Reload tmux config
bind r source-file ~/.tmux.conf

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

#set -g @plugin 'egel/tmux-gruvbox'
set -g @plugin 'o0th/tmux-nova'

set -g @nova-nerdfonts true
set -g @nova-nerdfonts-left 
set -g @nova-nerdfonts-right 

set -g @nova-pane-active-border-style "#44475a"
set -g @nova-pane-border-style "#282a36"
set -g @nova-status-style-bg "#4c566a"
set -g @nova-status-style-fg "#d8dee9"
set -g @nova-status-style-active-bg "#89c0d0"
set -g @nova-status-style-active-fg "#2e3540"
set -g @nova-status-style-double-bg "#2d3540"

set -g @nova-pane "#I#{?pane_in_mode,  #{pane_mode},}  #W"

set -g @nova-segment-mode "#{?client_prefix,Ω,ω}"
set -g @nova-segment-mode-colors "#78a2c1 #2e3440"

set -g @nova-segment-whoami "#(whoami)@#h"
set -g @nova-segment-whoami-colors "#78a2c1 #2e3440"

set -g @nova-rows 0
set -g @nova-segments-0-left "mode"
set -g @nova-segments-0-right "whoami"

# Other examples:
# set -g @plugin 'github_username/plugin_name'
# set -g @plugin 'git@github.com:user/plugin'
# set -g @plugin 'git@bitbucket.com:user/plugin'
set -g @plugin 'alexwforsythe/tmux-which-key'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
if "test ! -d ~/.tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm && ~/.tmux/plugins/tpm/bin/install_plugins'"
run '~/.tmux/plugins/tpm/tpm'
